import * as ExcelJS from "exceljs";
import { saveAs } from "file-saver";

export const exportExcel = async ({
  cols,
  data,
  sheetName = "files",
  creator = "Autogenerated",
  toastHandler = null,
  handleLoading,
  loadingKey = "exportExcel"
}) => {
  try {
    const now = new Date();
    handleLoading({ [loadingKey]: true });
    const workbook = new ExcelJS.Workbook();
    workbook.creator = creator;
    workbook.lastModifiedBy = creator;
    workbook.created = now;
    workbook.modified = now;
    workbook.lastPrinted = now;

    const sheet = workbook.addWorksheet(sheetName);
    sheet.state = "visible";
    sheet.columns = cols;

    data?.forEach((t) => {
      sheet.addRow(t);
    });

    const buffer = await workbook.xlsx.writeBuffer();
    const fileType =
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    const fileExtension = ".xlsx";

    const blob = new Blob([buffer], { type: fileType });
    saveAs(blob, sheetName + fileExtension);
  } catch (err) {
    console.error("Error al exportar a excel. " + e);
    toastHandler && toastHandler("Error al exportar a excel. " + e);
  } finally {
    handleLoading({ [loadingKey]: false });
  }
};
