export const filterLocale = {
  accept: "Si",
  addRule: "Agregar regla",
  am: "AM",
  apply: "Aplicar",
  cancel: "Cancelar",
  choose: "Escoger",
  chooseDate: "Escoger fecha",
  chooseMonth: "Escoger mes",
  chooseYear: "Escoger año",
  clear: "Limpiar",
  completed: "Completado",
  contains: "Contiene",
  custom: "Personalizado",
  dateAfter: "Fecha despues",
  dateBefore: "Fecha después",
  dateFormat: "dd/mm/yy",
  dateIs: "Fecha es",
  dateIsNot: "Fecha no es",
  dayNames: [
    "Domingo",
    "Lunes",
    "Martes",
    "Miércoles",
    "Jueves",
    "Viernes",
    "Sábado"
  ],
  dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
  dayNamesShort: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
  emptyFilterMessage: "No se encontraron resultados",
  emptyMessage: "No hay opciones disponibles",
  emptySearchMessage: "No se encontraron resultados",
  emptySelectionMessage: "Ninguna opción seleccionada",
  endsWith: "Termina con",
  equals: "Igual",
  fileSizeTypes: ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
  filter: "Filtro",
  firstDayOfWeek: 0,
  gt: "Mayor que",
  gte: "Mayor o igual que",
  lt: "Menos que",
  lte: "Menos o igual que",
  matchAll: "Coincidir todos",
  matchAny: "Coincidir cualquiera",
  medium: "Medio",
  monthNames: [
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre"
  ],
  monthNamesShort: [
    "Ene",
    "Feb",
    "Mar",
    "Abr",
    "May",
    "Jun",
    "Jul",
    "Ago",
    "Sep",
    "Oct",
    "Nov",
    "Dec"
  ],
  nextDecade: "Siguiente década",
  nextHour: "Siguiente hora",
  nextMinute: "Siguiente Minuto",
  nextMonth: "Siguiente mes",
  nextSecond: "Siguiente segundo",
  nextYear: "Siguiente año",
  noFilter: "Sin filtros",
  notContains: "No contiene",
  notEquals: "Diferente",
  now: "Ahora",
  passwordPrompt: "Ingrese la contraseña",
  pending: "Pendiente",
  pm: "PM",
  prevDecade: "Década anterior",
  prevHour: "Hora anterior",
  prevMinute: "Minuto anterior",
  prevMonth: "Mes anterior",
  prevSecond: "Segundo anterior",
  prevYear: "Año anterior",
  reject: "No",
  removeRule: "Eliminar regla",
  searchMessage: "{0} resultados disponibles",
  selectionMessage: "{0} items seleccionados",
  showMonthAfterYear: false,
  startsWith: "Empieza con",
  strong: "Fuerte",
  today: "Hoy",
  upload: "Subir",
  weak: "Débil",
  weekHeader: "Wk"
};
